<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <Compile Include="..\..\Services\WebViewRuntimeService.cs" Link="WebViewRuntimeService.cs" />
    <Compile Include="..\..\Models\SoftwareUpdate.cs" Link="SoftwareUpdate.cs" />
  </ItemGroup>
</Project>
